# Created by webjeda
#
#
# Use with caution. Wrong values may break the site

title: Fruit Treat
description: Healthy, Crispy, Crunchy and Tasty Fruit Treat, made with fruits naturally and organically cultivated in the heart of Western Ghats rich in medicinal Plants.

facebook: https://www.facebook.com/Fruit_Treat_India-1734956993200339/
twitter:
googleplus:
phone: +91-974-364-0415
email: info@fruittreat.com


sass: 
   style: compressed
   
   
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
  
plugins: 
    - jekyll-seo-tag